---
title: "Quotes"
---

This section is for quotes from books I read but didn't review, or quotes I found particularly meaningful. 

# Wisdom

> Almost everything will work again if you unplug it for a few minutes, including you.
> 
> --- Anne Lamott. “Almost Everything”.

---

> The part I like most about Luke’s story is the lawyer who tries to trap Jesus with a trick question about who his neighbor is, so he can find a loophole in Jesus’ appeal to love thy neighbor. The lawyer wants to narrowly define neighbor so he can say, “In my view, this person is not a neighbor, so I can continue to hate, to fear him and treat him as badly as I want,” which is straight from today’s front pages. That, I am sorry to admit, is what I might have tried.
>
> --- Anne Lamott. “Almost Everything”.

---

> The opposite of a profound truth is another profound truth.
>
> --- Niels Bohr

# Insight

> Premodern games such as chess assumed a stagnant economy. You begin a game of chess with sixteen pieces, and you never finish a game with more. In rare cases a pawn may be transformed into a queen, but you cannot produce new pawns nor upgrade your knights into tanks. So chess players never have to consider investment. In contrast, many modern board games and computer games focus on investment and growth. Particularly telling are civilisation-style strategy games, such as Minecraft, The Settlers of Catan or Sid Meier’s Civilization. The game may be set in the Middle Ages, the Stone Age or some imaginary fairy land, but the principles always remain the same –and are always capitalist. Your aim is to establish a city, a kingdom or maybe an entire civilisation. You begin from a very modest base, perhaps just a village and its nearby fields. Your assets provide you with an initial income of wheat, wood, iron or gold. You then have to invest this income wisely. You have to choose between unproductive but still necessary tools such as soldiers, and productive assets such as more villages, fields and mines. The winning strategy is usually to invest the barest minimum in non-productive essentials, while maximising your productive assets. 
>
> --- Yuval Noah Harari. "Homo Deus".
 
---
 
> The first time you meet Winston you see all his faults,’ she told him, ‘and the rest of your life you spend in discovering his virtues.
>
> --- Andrew Roberts. “Churchill: Walking with Destiny”.  

---

> Everything is more beautiful because we are doomed. 
>
> --- Homer. "The Iliad".

---

>I learned that behavior that looks lazy or withdrawn to someone perched far above the poverty line can actually be a pacing technique. People like Crystal or Larraine cannot afford to give all their energy to today’s emergency only to have none left over for tomorrow’s.
>
> --- Matthew Desmond. "Evicted".

---

>Development is a voyage with more shipwrecks than navigators.
>
> --- Eduardo Galeano. "Open Veins of Latin America".


# Beautiful Writing

> Eddie convinced Flako to lend him his gun, a .380, which Flako did reluctantly, urging Eddie not to do anything stupid. Flako was placid and humble, and Eddie always thought that he seemed out of his element. A year and a half later, Flako reportedly threw himself out of a third-floor window, and Eddie sometimes wonders if his distress didn’t find its roots in what Eddie did with that gun.
>
> --- Alex Kotlowitz. “An American Summer”. 

---

> 几個月來產生的對共產黨的好感被指導員一槍打碎了。
>
> --- 莫言《红高粱家族》

# Inspirational

>Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails.
>
> --- Mark Twain

---

> People are supposed to forgo earnings opportunities in order to lead richer lives. 
>
> --- David Brook. "Bobos in Paradise: The New Upper Class and How They Got There".

---

> A little bit of slope makes up for a lot of Y-intercept... But I didn’t really mean in a mathematical sense, I think this is a pretty good guideline for life also.  What I mean is that how fast you learn is a lot more important than how much you know to begin with.  So in general I say that people emphasize too much how much they know and not how fast they’re learning.
>
> --- John Ousterhout

---

> You can never cross the ocean until you have the courage to lose sight of the shore.
>
> --- André Gide



